import requests

response = requests.get("https://query.dropbase.io/mh94TPFpNoX4YPJDE72G9c",
 headers={
   "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhYmFzZUlkIjoibWg5NFRQRnBOb1g0WVBKREU3Mkc5YyIsImFjY2Vzc1Blcm0iOiJmdWxsIiwidG9rZW5JZCI6IlhlTTVaYkdIbE55NldmeG9HbkdLN3BOU1dNN3hISzc3b3RMeXRYRFpraXUzZEZPRmgxa1JVN1dtcFhtSkxZU0MiLCJpYXQiOjE2MTE2OTAzODQsImV4cCI6MTkyNzA1MDM4NCwiaXNzIjoiZHJvcGJhc2UuaW8iLCJzdWIiOiJrdEg0UmI1Skp3RFVReUcyYW16Y1JyIn0.r2hs3OSqujRw1TkVvKsXDCi9Ci8QfGvS6KJIBdqVgSs"
 }
)

print(response)
print(response.text)
