name: Fetch V2ray Nodes On Schedule

on:
  schedule:
    - cron: '01 2 * * *'
  workflow_dispatch:
  
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies and run script
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python ${{ github.workspace }}/v2ray_toolkit/fetch-wz2023jd.py

      - name: Check for Changes
        id: check_changes
        run: |
          if [[ -n "$(git diff --exit-code)" ]]; then
            echo "Changes detected."
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "No changes detected."
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Git config, commit, pull (--rebase) and push changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Crawl v2ray nodes @$(TZ='Asia/Shanghai' date '+%Y-%m-%d %H:%M:%S') 🛫"
          git pull --rebase origin main
          git push
